apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: debug-config
spec:
  args:
    - --debug
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-argocd-login
spec:
  package: 'ghcr.io/projectkerberus/xp-provider-argocd-login:0.2.0'
  packagePullPolicy: IfNotPresent
  packagePullSecrets: 
  - name: cr-token
  controllerConfigRef:
    name: debug-config
