apiVersion: v1
kind: Namespace
metadata:
  name: krateo-system
---
apiVersion: argocd.krateo.io/v1alpha1
kind: Token
metadata:
  name: krateo-dashboard-argocd-token
spec:
  forProvider:
    account: krateo-dashboard
    writeTokenSecretToRef:
      name: krateo-dashboard-argocd-token
      key: authToken
      namespace: krateo-system
  providerConfigRef:
    name: provider-argocd-token-config