name: release

on:
  push:
    tags: [ 'v*' ]

jobs:
  package:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build
        run: make image.build
      
      - name: Login to CR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Package
        run: make image.push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build xpkg
        uses: crossplane-contrib/xpkg-action@master
        with:
          channel: ${{ github.event.inputs.channel }}
          version: ${{ github.event.inputs.version }}
          command: build provider -f package --name=xpkg-provider-argocd-token
        
      - name: Push xpkg
        uses: crossplane-contrib/xpkg-action@master
        with:
          command: push provider -f package/xpkg-provider-argocd-token.xpkg ghcr.io/krateoplatformops/xpkg-provider-argocd-token:v0.1.7